title: bsalmankurt homepage
page-top-title: Bahadır Salmankurt
top-section-bg-text: Hesaplamalı Nanobilim
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
