title: bsalmankurt homepage
page-top-title: Bahadır Salmankurt
top-section-bg-text: Hesaplamalı Nanobilim
home-subtitle: Dr. Bahadır SALMANKURT
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
